### ISSUE TITLE
Role 엔티티 추가 및 회원가입, 로그인 API 응답 데이터 수정

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-BE-Spring#19]
### Role, MemberRole 엔티티 추가
- MemberRole은 Member와 Role에 대해 ManyToOne 관계
- UserDetails에 회원 등급을 List 형태로 보관
- 등급(권한)이 추가되는 형식으로 변경
- 모든 Role을 DB에 추가하는 설정 파일 추가
### 회원가입, 로그인 API 응답 데이터 수정
- 회원 정보 응답 -> Front 단에서 Redux를 이용한 상태관리를 위함
- Member 엔티티 생성자 파라미터에서 학번 제거 -> 생성자에서 이메일 파싱하여 저장

## Todo list
- [x] Role, MemberRole 엔티티 추가
- [x] 회원가입, 로그인 API 응답 데이터 수정
- [x] 테스트 코드 수정
