### ISSUE TITLE
회원 탈퇴 API 추가

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-BE-Spring#35]
### 회원 탈퇴 API
- 개인 정보(실명, 학과, 학번 등) 파기
- 회원 탈퇴 시, 기존 게시글, 댓글, 좋아요 등 활동 내역은 그대로 유지.
    - 작성자 명: `알 수 없음`으로 표기
- 재가입 시, 기존 활동 내역은 그대로 남아 있음
- 로그인 API 로직 수정 필요
    - 이미 존재하는 userId라도, 탈퇴한 회원이라면 회원가입 페이지로 이동
    - 재가입 로직 -> 회원가입 API에 추가
        - 탈퇴한 회원인 경우, 해당 정보로 변경 및 권한 수정
        - 재가입 불가 회원인 경우, 400 응답

## Todo list
- [x] 회원 탈퇴 API 추가
- [x] 로그인 API 로직 수정
- [x] 테스트 코드 작성
