### ISSUE TITLE
그룹 가입 신청 API 추가

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-BE-Spring#51]
### 그룹 가입 신청 API 추가
- 구글 폼 제출 이후, 그룹 가입 신청 버튼을 클릭하면 호출
- 각 그룹 운영진이 가입 신청 목록을 확인하여 승인 하는 구조
- GroupRoles : `{APPLICANT, MEMBER, EXECUTIVE, PRESIDENT}` 추가
    - 가입 신청 시, 해당 회원을 `APPLICANT`로 GroupMember 엔티티에 추가

## Todo list
- [x] 그룹 가입 신청 API 구현
- [x] 그룹 엔티티 추가
- [ ] 테스트 코드 작성
