### ISSUE TITLE
권한 부여/요청 목록 조회 API 추가 등

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-BE-Spring#58]
## Feature Description
- 권한 부여/요청 목록 조회 API 추가
- 권한 요청 API 로직 수정
    - 권한 요청 시, 바로 권한을 얻는 로직 -> 권한 요청 목록에 추가 후, 임원이 승인하는 로직

## Todo list
- [x] 권한 부여/요청 목록 조회 API 추가
- [x] 권한 요청 API 로직 수정
- [ ] 테스트 코드 작성
