### ISSUE TITLE
Advice, Config, Util, 결과/예외 response, BusinessException 추가

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-BE-Spring#8]
## Feature Description
- 글로벌 예외 처리 핸들러 추가
    - 자바, 스프링 표준 예외와 커스텀 예외를 처리하는 Hlobal Execption Handler Advice 추가
- Redis, Security, Jwt 설정 클래스 추가
    - host, port 연동하여 Lettues 구현체 bean 등록
    - redisTemplate bean 등록
    - Security 설정 + cors 설정
- Redis, Jwt 유틸 클래스 추가
    - Redis, Jwt 관련 편의 메소드 구현
- Business Exception 추가
    - 해당 클래스를 상속한 커스텀 예외들을 advice에서 하나의 예외 핸들러로 처리
- ResultCode, ResultResponse, ErrorCode, ErrorResponse 추가
    - 응답 형식 통일 + 응답 메시지를 모아둔 Code를 추가하여 역할과 책임을 분리

## Todo list
- [x] GlobalExceptionHandler 추가
- [x] RedisConfig, SecurityConfig, JwtFilter 추가
- [x] RedisUtil, JwtUtil 추가
- [x] Business Exception 추가
- [x] ResultCode, ResultRespone, ErrorCode, ErrorResponse 추가
