### ISSUE TITLE
그룹원 검색 API 추가 등

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-BE-Spring#86]
## Feature Description
- 그룹원 검색 API 추가
    - 검색어, 성별, 학적, 상태, 학년
    - 권한 검색은 기존의 그룹원 목록 조회 API를 사용
- 회원 권한 부여 API 로직 수정
    - 그룹원, 그룹 임원만 부여 가능
    - 그룹장은 따로 API를 추가하여 부여할 수 있도록 수정 
- 그룹장 권한 부여 API 추가
- 그룹 가입 신청 API 예외 처리 추가
    - 가입 신청 중복 방지

## Todo list
- [x] 그룹원 검색 API 추가
- [x] 회원 권한 부여 API 로직 수정
- [x] 그룹장 권한 부여 API 추가
- [x] 그룹 가입 신청 API 예외 처리 추가
